# Generated by Django 5.0.1 on 2024-02-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cohormember_is_active_cohort_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohormember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
