# Generated by Django 5.0.1 on 2024-02-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_name_classschedule_classattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classattendance',
            name='is_present',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_repeated',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
