# Generated by Django 5.0.1 on 2024-02-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classattendance_is_present_classschedule_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classattendance',
            name='is_present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='is_repeated',
            field=models.BooleanField(default=True),
        ),
    ]
